const {loadApp}=require('./applib.js');
let fails=0,tests=0;const ok=(c,m)=>{tests++;if(!c){fails++;console.log('FAIL:',m);}else console.log('ok  ',m);};
const close=(a,b)=>Math.abs(a-b)<1e-6;
let A=loadApp({meta:{fee:100,bank:100,minBet:1,maxBet:10},players:{},matches:{},bets:{}},{});
const calc=A.sandbox.calcMatch, detect=A.sandbox.detectDrawOK;
const M=(d,w,b)=>({drawOK:d,settled:!!w,winner:w||null,bets:b});
const B={p1:{team:'A',stake:40},p2:{team:'X',stake:10},p3:{team:'B',stake:50}};
let c=calc(M(true,'X',B));
ok(close(c.payouts.p2,100),'draw X: X-bettor splits whole pool (10->100)');
ok(c.payouts.p1===0&&c.payouts.p3===0,'draw X: A/B bettors get 0');
ok(close(c.coefX,10),'coefX = pool/sumX = 10');
c=calc(M(true,'A',B));
ok(close(c.payouts.p1,100)&&c.payouts.p2===0&&c.payouts.p3===0,'A wins: 40->100, others 0');
c=calc(M(true,'VOID',B));
ok(c.refunded&&c.payouts.p1===40&&c.payouts.p2===10&&c.payouts.p3===50,'VOID: everyone refunded');
const B2={p1:{team:'A',stake:5},p2:{team:'B',stake:5}};
c=calc(M(false,'X',B2));
ok(c.refunded&&c.payouts.p1===5&&c.payouts.p2===5,'knockout winner=X, no X bets -> refund (unchanged)');
c=calc(M(true,'X',B2));
ok(c.refunded,'draw result but no X bettors -> refund all');
ok(detect('fifa.world','Round of 16')===false,'detect knockout -> no draw');
ok(detect('fifa.world','Group A - Matchday 1')===true,'detect group -> draw');
ok(detect('eng.1','')===true,'detect league slug -> draw');
ok(detect('uefa.champions','Final')===false,'detect final -> no draw');
console.log((fails?('FAILED '+fails+'/'+tests):('ALL PASS '+tests+'/'+tests)));process.exit(fails?1:0);
